### AUTH
### register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "user_name": "meep",
  "email": "meep@yeet.com"
}

### fetch code
POST http://localhost:3000/api/auth/code
Content-Type: application/json

{
  "email": "meep@blargh.com",
  "user_name": "john"
}
