### AUTH
### register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "user_name": "meep",
  "email": "meep@yeet.com"
}

### fetch code
POST http://localhost:3000/api/auth/code
Content-Type: application/json

{
  "email": "meep@yeet.com",
  "user_name": "john"
}

### TEAM
### create team
POST http://localhost:3000/api/team/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyIjp7InVzZXJfaWQiOiIwZGM4MjliZS02ZjcyLTQ3ZDQtYmZkMi1mNzVlMTE3MWQ3ZjEiLCJ1c2VyX25hbWUiOiJqb2huIiwiZW1haWwiOiJtZWVwQHllZXQuY29tIiwiaXNfYWN0aXZlIjp0cnVlLCJpc19lbWFpbF92ZXJpZmllZCI6ZmFsc2V9LCJleHAiOjE2OTE5NjQxODl9.ynZs8fa9zbhPtl5yw2chkrP2rRYOJuGuyg2kiJO2zjE

{
  "team_name": "waffles"
}

